### ISSUE TITLE
Error when trying to download kinetics test set

### ISSUE THREAD

**Issue by pedro-abreu** [activitynet/ActivityNet#15]
After running download.py I get the following error, only with the test set. The other two work fine.

```
Traceback (most recent call last):
  File "download.py", line 192, in <module>
    main(**vars(p.parse_args()))
  File "download.py", line 157, in main
    label_to_dir = create_video_folders(dataset, output_dir, tmp_dir)
  File "download.py", line 23, in create_video_folders
    for label_name in dataset['label-name'].unique():
  File "/home/pedro/anaconda2/lib/python2.7/site-packages/pandas/core/frame.py", line 1964, in __getitem__
    return self._getitem_column(key)
  File "/home/pedro/anaconda2/lib/python2.7/site-packages/pandas/core/frame.py", line 1971, in _getitem_column
    return self._get_item_cache(key)
  File "/home/pedro/anaconda2/lib/python2.7/site-packages/pandas/core/generic.py", line 1645, in _get_item_cache
    values = self._data.get(item)
  File "/home/pedro/anaconda2/lib/python2.7/site-packages/pandas/core/internals.py", line 3590, in get
    loc = self.items.get_loc(item)
  File "/home/pedro/anaconda2/lib/python2.7/site-packages/pandas/core/indexes/base.py", line 2444, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/_libs/index.pyx", line 132, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 154, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1210, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1218, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'label-name'
```

**Comment by HumamAlwassel** [comment]
Thank you for your interest in ActivityNet. Please refer to issue #6
