### ISSUE TITLE
TypeError: Object of type 'bytes' is not JSON serializable

### ISSUE THREAD

**Issue by BarakBat** [activitynet/ActivityNet#34]
Hi, I had this problem:

Traceback (most recent call last):
  File "download.py", line 220, in <module>
    main(**vars(p.parse_args()))
  File "download.py", line 200, in main
    fobj.write(json.dumps(status_lst))
  File "/home/anaconda3/lib/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/home/anaconda3/lib/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/anaconda3/lib/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/anaconda3/lib/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'bytes' is not JSON serializable

I'll be happy if you have any clue, about this problem.
Thanks.

**Comment by escorciav** [comment]
Sorry to hear that. Unfortunately, it's difficult to know what's going on here. However, it seems that you are trying to run the code using `python-3` while the [environment](https://github.com/activitynet/ActivityNet/blob/master/Crawler/Kinetics/environment.yml) and code use `python-2`.

I would try again using the conda environment or similar dependency version.
