### ISSUE TITLE
How can I download the test set of Kinetics

### ISSUE THREAD

**Issue by wlgcqh** [activitynet/ActivityNet#6]

**Comment by wlgcqh** [comment]
@cabaf @escorciav

**Comment by HumamAlwassel** [comment]
Dear,

You can download the test subset using our [crawler script](https://github.com/activitynet/ActivityNet/tree/master/Crawler/Kinetics) - we added the `kinetics_test.csv` file from DeepMind website to the data folder for your convenience. 

Best,
Humam

**Comment by chihyaoma** [comment]
Hi, 

There is no label in the test set, so I guess the original downloading script won't work. If I run the downloading script directly with `kinetics_test.csv`, here is what I got. 

```
Traceback (most recent call last):
  File "download.py", line 194, in <module>
    main(**vars(p.parse_args()))
  File "download.py", line 157, in main
    label_to_dir = create_video_folders(dataset, output_dir, tmp_dir)
  File "download.py", line 23, in create_video_folders
    for label_name in dataset['label-name'].unique():
  File "/home/mli/cyma/anaconda3/envs/kinetics/lib/python2.7/site-packages/pandas/core/frame.py", line 2059, in __getitem__
    return self._getitem_column(key)
  File "/home/mli/cyma/anaconda3/envs/kinetics/lib/python2.7/site-packages/pandas/core/frame.py", line 2066, in _getitem_column
    return self._get_item_cache(key)
  File "/home/mli/cyma/anaconda3/envs/kinetics/lib/python2.7/site-packages/pandas/core/generic.py", line 1386, in _get_item_cache
    values = self._data.get(item)
  File "/home/mli/cyma/anaconda3/envs/kinetics/lib/python2.7/site-packages/pandas/core/internals.py", line 3543, in get
    loc = self.items.get_loc(item)
  File "/home/mli/cyma/anaconda3/envs/kinetics/lib/python2.7/site-packages/pandas/indexes/base.py", line 2136, in get_loc
    return self._engine.get_loc(self._maybe_cast_indexer(key))
  File "pandas/index.pyx", line 132, in pandas.index.IndexEngine.get_loc (pandas/index.c:4433)
  File "pandas/index.pyx", line 154, in pandas.index.IndexEngine.get_loc (pandas/index.c:4279)
  File "pandas/src/hashtable_class_helper.pxi", line 732, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13742)
  File "pandas/src/hashtable_class_helper.pxi", line 740, in pandas.hashtable.PyObjectHashTable.get_item (pandas/hashtable.c:13696)
KeyError: 'label-name'
```

**Comment by HumamAlwassel** [comment]
Dear Chih-Yao,

Yes, you are right! The original code won't work since it looks for a `label-name` column in the csv file to download the video in the label subfolders. You can get around this by either commenting that part of the code (as you mentioned), or by adding a `label-name` column to the csv file with a the same value for all rows (e.g. `test-label`). The second workaround will download all the videos in one subfolder named `/test-label`.

Hope this helps,
Humam
