### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by cloveropen** [activitynet/ActivityNet#87]
Hi，when i run "python download.py ./data/kinetics-600_train.csv dd_train ",after a while，get the error:

Traceback (most recent call last):
  File "d:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 431, in _process_worker
    r = call_item()
  File "d:\ProgramData\Anaconda3\lib\site-packages\joblib\externals\loky\process_executor.py", line 285, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "d:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 595, in __call__
    return self.func(*args, **kwargs)
  File "d:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 262, in __call__
    return [func(*args, **kwargs)
  File "d:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 262, in <listcomp>
    return [func(*args, **kwargs)
  File "download.py", line 132, in download_clip_wrapper
    downloaded, log = download_clip(row['video-id'], output_filename,
  File "download.py", line 100, in download_clip
    tmp_filename = glob.glob('%s*' % tmp_filename.split('.')[0])[0]
IndexError: list index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "download.py", line 223, in <module>
    main(**vars(p.parse_args()))
  File "download.py", line 194, in main
    status_lst = Parallel(n_jobs=num_jobs)(delayed(download_clip_wrapper)(
  File "d:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 1061, in __call__
    self.retrieve()
  File "d:\ProgramData\Anaconda3\lib\site-packages\joblib\parallel.py", line 940, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "d:\ProgramData\Anaconda3\lib\site-packages\joblib\_parallel_backends.py", line 542, in wrap_future_result
    return future.result(timeout=timeout)
  File "d:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 439, in result
    return self.__get_result()
  File "d:\ProgramData\Anaconda3\lib\concurrent\futures\_base.py", line 388, in __get_result
    raise self._exception
IndexError: list index out of range

**Comment by tsuyoshily** [comment]
I'm facing the same problem.
Did you find any solution?

**Comment by preetshah7** [comment]
I am facing the same error, it downloads some videos and then shows this error. Please help

**Comment by obeychoi0120** [comment]
in 'tmp_filename = glob.glob('%s' % tmp_filename.split('.')[0])[0]' : 

when i check the variable 'tmp_filename', It is empty. 
I deleted the very outer indexing [0] as now, but i think it is not the perfect way.

**Comment by Allencheng97** [comment]
I got the same problem. I think this [repo](https://github.com/cvdfoundation/kinetics-dataset) might be helpful. It's easier then debug for official scripts.

**Comment by Allencheng97** [comment]
I create a new [repo ](https://github.com/Allencheng97/kinetics-dataset-aria) using aria2c to download. Feel free to use this code.
