### ISSUE TITLE
Could not find conda environment: kinetics

### ISSUE THREAD

**Issue by DungVo1507** [activitynet/ActivityNet#88]
Hi @h0pbeat 
I can't find the kinetics environment so when I run the command line `source activate kinetics` I get the error `Could not find conda environment: kinetics`

`# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/conda/exceptions.py", line 1079, in __call__
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/conda_env/cli/main.py", line 80, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/usr/local/lib/python3.6/site-packages/conda_env/cli/main_create.py", line 88, in execute
        spec = specs.detect(name=name, filename=get_filename(args.file), directory=os.getcwd())
      File "/usr/local/lib/python3.6/site-packages/conda_env/specs/__init__.py", line 43, in detect
        if spec.can_handle():
      File "/usr/local/lib/python3.6/site-packages/conda_env/specs/yaml_file.py", line 18, in can_handle
        self._environment = env.from_file(self.filename)
      File "/usr/local/lib/python3.6/site-packages/conda_env/env.py", line 166, in from_file
        return from_yaml(yamlstr, filename=filename)
      File "/usr/local/lib/python3.6/site-packages/conda_env/env.py", line 143, in from_yaml
        data = yaml_safe_load(yamlstr)
      File "/usr/local/lib/python3.6/site-packages/conda/common/serialize.py", line 67, in yaml_safe_load
        return yaml.safe_load(string, version="1.2")
      File "/usr/local/lib/python3.6/site-packages/ruamel_yaml/main.py", line 668, in safe_load
        return load(stream, SafeLoader, version)
      File "/usr/local/lib/python3.6/site-packages/ruamel_yaml/main.py", line 639, in load
        return loader._constructor.get_single_data()  # type: ignore
      File "/usr/local/lib/python3.6/site-packages/ruamel_yaml/constructor.py", line 104, in get_single_data
        return self.construct_document(node)
      File "/usr/local/lib/python3.6/site-packages/ruamel_yaml/constructor.py", line 114, in construct_document
        for dummy in generator:
      File "/usr/local/lib/python3.6/site-packages/ruamel_yaml/constructor.py", line 611, in construct_yaml_map
        value = self.construct_mapping(node)
      File "/usr/local/lib/python3.6/site-packages/ruamel_yaml/constructor.py", line 356, in construct_mapping
        return BaseConstructor.construct_mapping(self, node, deep=deep)
      File "/usr/local/lib/python3.6/site-packages/ruamel_yaml/constructor.py", line 236, in construct_mapping
        value = self.construct_object(value_node, deep=deep)
      File "/usr/local/lib/python3.6/site-packages/ruamel_yaml/constructor.py", line 159, in construct_object
        data = constructor(self, node)
      File "/usr/local/lib/python3.6/site-packages/ruamel_yaml/constructor.py", line 631, in construct_undefined
        node.start_mark)
    ruamel_yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/tuple'
      in "<unicode string>", line 2, column 11:
        channels: !!python/tuple
                  ^ (line: 2)

`$ /usr/local/bin/conda-env create -f environment.yml`

  environment variables:
                 CIO_TEST=<not set>
  CONDA_AUTO_UPDATE_CONDA=false
               CONDA_ROOT=/usr/local
           CURL_CA_BUNDLE=<not set>
          LD_LIBRARY_PATH=/usr/lib64-nvidia
             LIBRARY_PATH=/usr/local/cuda/lib64/stubs
                     PATH=/usr/local/nvidia/bin:/usr/local/cuda/bin:/usr/local/sbin:/usr/local/b
                          in:/usr/sbin:/usr/bin:/sbin:/bin:/tools/node/bin:/tools/google-cloud-
                          sdk/bin:/opt/bin
               PYTHONPATH=/env/python
           PYTHONWARNINGS=ignore:::pip._internal.cli.base_command
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>

     active environment : None
       user config file : /root/.condarc
 populated config files : 
          conda version : 4.10.3
    conda-build version : not installed
         python version : 3.6.13.final.0
       virtual packages : __cuda=11.2=0
                          __linux=5.4.104=0
                          __glibc=2.27=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /usr/local  (writable)
      conda av data dir : /usr/local/etc/conda
  conda av metadata url : None
           channel URLs : https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /usr/local/pkgs
                          /root/.conda/pkgs
       envs directories : /usr/local/envs
                          /root/.conda/envs
               platform : linux-64
             user-agent : conda/4.10.3 requests/2.18.4 CPython/3.6.13 Linux/5.4.104+ ubuntu/18.04.5 glibc/2.27
                UID:GID : 0:0
             netrc file : None
           offline mode : False

An unexpected error has occurred. Conda has prepared the above report.

If submitted, this report will be used by core maintainers to improve
future releases of conda.
Would you like conda to send this report to the core maintainers?

[y/N]: y
Upload successful.

Thank you for helping to improve conda.
Opt-in to always sending reports (and not see this message again)
by running

    $ conda config --set report_errors true

Could not find conda environment: kinetics
You can list all discoverable environments with `conda info --envs`.

Requirement already up-to-date: youtube-dl in /usr/local/lib/python3.6/site-packages (2021.6.6)
conda 4.10.3 requires ruamel_yaml_conda>=0.11.14, which is not installed.`
Hope you help!

**Comment by turtleman99** [comment]
I met the same issue and am stuck.

**Comment by Jibanul** [comment]
The environment.yml in this repo seems outdated. I found this updated environment file that works. [link](https://github.com/LukasHedegaard/ActivityNet/blob/update-kinetics-crawler-environment/Crawler/Kinetics/environment.yml)

More info about this issue and solution can be found in #73

**Comment by soumyadbanik** [comment]
> The environment.yml in this repo seems outdated. I found this updated environment file that works. [link](https://github.com/LukasHedegaard/ActivityNet/blob/update-kinetics-crawler-environment/Crawler/Kinetics/environment.yml)
> 
> More info about this issue and solution can be found in #73

Thanks a lot
